spring:
  profiles:
    active: dev

  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000

logging:
  file:
    name: logs/auth-service.log
  level:
    root: INFO